### ISSUE TITLE
how to run detectron type dataset in your code?

### ISSUE THREAD

**Issue by zimingzhong** [qqlu/Amodal-Instance-Segmentation-through-KINS-Dataset#16]
My dataset can run in the git you give (git clone https://github.com/roytseng-tw/mask-rcnn.pytorch.git) in the README.md's Getting started.
But when I try to run it on your code, I got an error.
    `File "/root/project/Amodal-Instance-Segmentation-through-KINS-Dataset/Reference Code/lib/datasets/json_dataset_amodalinmodalseg.py", line 40, in <module>
    from pycocotools.coco_amodalinmodalseg import COCO
ModuleNotFoundError: No module named 'pycocotools.coco_amodalinmodalseg'`
And if I change `from pycocotools.coco_amodalinmodalseg import COCO` to `from pycocotools.coco import COCO`。
I will get another error.
`amodal_full_mask = np.array(mask_util.decode(entry['amodal_full']), dtype=np.float32) ` 
 in json_dataset_amodalinmodalseg.py 236
because dict `entry` has no `amdoal_full`key.

Looking forward to your response. Thanks for your help.
My email: ziming.zhong@foxmail.com

**Comment by zimingzhong** [comment]
When I change all `import json_dataset_amodalinmodalseg` to `import json_dataset_amodal` because the latter has no `pycocotools.coco_amodalinmodalseg`, but I  get an error 
`File "/root/project/Amodal-Instance-Segmentation-through-KINS-Dataset/Reference Code/lib/datasets/json_dataset_amodal.py", line 242, in _add_gt_annotations
    valid_segms_amodal.append(obj['amodal'])
KeyError: 'amodal'`

I already know you changed the cocoapi for a specific issue, but how to change the code to adapt detectron type dataset.
Thanks!

**Comment by qqlu** [comment]
Hi, I am sorry to reply late.

Yes, I indeed modify the cocoapi to train and evaluate amodal and inmodal masks simultaneously. The main modification for COCOAPI is changing the "segm" to "amodal" or "inmodal". That means the relevant api for now codebase like detectron2 or mmdetection need modification.

Another way to train amodal mask only is to change the json annotation "amodal" to "segm".

**Comment by zimingzhong** [comment]
Hi, qqlu

I have changed `from .json_dataset_amodalinmodalseg import JsonDatasetAmodalInmodalSeg as JsonDataset` to `from .json_dataset import JsonDataset`.  Is that the right change? When I find any dict without the right key name in `roidb.py`, I will change it. Even I commented all codes including the word `in` because they are for 'inmodal'. 
Like `flipped_entry['segms_inmodal'] = segm_utils.flip_segms(
            entry['segms_inmodal'], entry['height'], entry['width']
        )`
        `
        flipped_entry['segms_invisible_full'] = segm_utils.flip_segms(
            entry['segms_invisible_full'], entry['height'], entry['width']
        )`
Then I got a more strange error.
 `KeyError: 'Traceback (most recent call last):\n  File "/root/Anacondas/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/root/Anacondas/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/root/project/Amodal-Instance-Segmentation-through-KINS-Dataset/Reference Code/lib/roi_data/loader.py", line 27, in __getitem__\n    blobs, valid = get_minibatch(single_db)\n  File "/root/project/Amodal-Instance-Segmentation-through-KINS-Dataset/Reference Code/lib/roi_data/minibatch.py", line 35, in get_minibatch\n    valid = roi_data.rpn.add_rpn_blobs(blobs, im_scales, roidb)\n  File "/root/project/Amodal-Instance-Segmentation-through-KINS-Dataset/Reference Code/lib/roi_data/rpn.py", line 68, in add_rpn_blobs\n    gt_rois = entry[\'boxes_amodal\'][gt_inds, :] * scale\nKeyError: \'boxes_amodal\'\n'`

 And if I just want to train an amodal modal, am I on the right way to change codes? All the issues are the same, whatever I use my dataset or KINS dataset. And what is specific mean by "change the json annotation 'amodal' to 'segm'". Just simply change the data name from 'amdoal' to 'segm' in json file? My dataset already can run on detectron1(git clone https://github.com/roytseng-tw/mask-rcnn.pytorch.git).

Thanks for your help. @qqlu

**Comment by qqlu** [comment]
Hi, if you want to train an amodal mask, changing the key "amodal" to "segm" in the json file is most convenient way.

**Comment by zimingzhong** [comment]
All I need to do is changing 'segmentation' to 'sgem'?
![image](https://user-images.githubusercontent.com/55894447/91026870-eea61500-e62d-11ea-9484-9b4f54a3d352.png)

**Comment by qqlu** [comment]
You could refer to this code. cvbase is only used to load json file.

import cvbase as cvb

base_path = "/data/qilu/datasets/amodal/"

ann_path  = os.path.join(base_path, "train.json")
save_path = os.path.join(base_path, "newtrain2017.json")
aa = cvb.load(ann_path)

aa_new = {}
for key in ["info", "licenses", "categories", "images", "annotations"]:
	aa_new[key] = aa[key]

### change annotations
for index in range(len(aa_new["annotations"])):
	aa_new["annotations"][index]["segmentation"] = aa_new["annotations"][index]["amodal"]
	aa_new["annotations"][index]["bbox"] = aa_new["annotations"][index]["???"]

cvb.dump(aa_new, save_path)

**Comment by qqlu** [comment]
In my method, I also used the occlusion part of the whole image. I think the best way is to use MMDetection or detectron2. You could only put the multi-view encoding module into the new codebase. Pytorch-detectron2 is too old. 

From my experience, it is more convenient for amodal instance segmentation.

**Comment by zimingzhong** [comment]
Thanks for providing code. But my dataset already was set in that type.
![image](https://user-images.githubusercontent.com/55894447/91028980-c79d1280-e630-11ea-98b0-e5f8be2eb071.png)

And When I use the KINS dataset, I will encounter the same issue. So maybe these issues are not about dataset.
